[workspace]
members = [
    "canister/api",
    "canister/impl",
    "libraries/canister_logger",
    "libraries/types",
]

[patch.crates-io]
ic-cdk = { git = "https://github.com/hpeebles/cdk-rs", rev = "506c0cf38a728318f99c692afc26452acd2236b8" }
ic-ledger-types = { git = "https://github.com/hpeebles/cdk-rs", rev = "506c0cf38a728318f99c692afc26452acd2236b8" }